services:
  web:
    build: .
    ports:
      - "5500:8000"
    environment:
      - DATA_PATH=data/houses.csv
      - MODEL_PATH=models/regression.joblib
      - SENTIMENT_ANALYSIS_MODEL_NAME=philschmid/tiny-bert-sst2-distilled
