[project]
name = "micro-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.2",
    "pandas>=2.2.3",
    "scikit-learn>=1.5.2",
    "uvicorn>=0.32.0",
]
