name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
          ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:${{ github.sha }}
    
    - name: SSH and pull Docker image on VM
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VM_MICRO_MLOPS_HOST }}
        username: ${{ secrets.VM_MICRO_MLOPS_USERNAME }}
        password: ${{ secrets.VM_MICRO_MLOPS_PASSWORD }}
        port: 22
        script: |
          cd camil.ziane/micro-mlops
          git pull origin main
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-fastapi-app:latest
          docker compose pull
          docker compose down
          docker compose up --build -d 
